#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"

TARGET_DIR="$ROOT/target"
REPORT_DIR="$TARGET_DIR/reports"
LIB_DIR="$ROOT/lib"
SRC_DIR="$ROOT/src/main/java"
TEST_SRC_DIR="$ROOT/src/test/java"

mkdir -p "$TARGET_DIR/classes" "$TARGET_DIR/test-classes" "$REPORT_DIR"

JAVA_HOME="${JAVA_HOME:-}"
if [ -z "$JAVA_HOME" ]; then
  if command -v /usr/libexec/java_home >/dev/null 2>&1; then
    JAVA_HOME="$(/usr/libexec/java_home -v1.8 2>/dev/null || true)"
  fi
fi

if [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ] && [ -x "$JAVA_HOME/bin/javac" ]; then
  JAVAC="$JAVA_HOME/bin/javac"
  JAVA="$JAVA_HOME/bin/java"
else
  JAVAC="javac"
  JAVA="java"
fi

JACOCO_VERSION="0.8.10"
JACOCO_AGENT="$LIB_DIR/org.jacoco.agent-$JACOCO_VERSION-runtime.jar"
JACOCO_CLI="$LIB_DIR/org.jacoco.cli-$JACOCO_VERSION-nodeps.jar"

if [ ! -f "$JACOCO_AGENT" ]; then
  curl -L -o "$JACOCO_AGENT" "https://repo1.maven.org/maven2/org/jacoco/org.jacoco.agent/$JACOCO_VERSION/org.jacoco.agent-$JACOCO_VERSION-runtime.jar"
fi

if [ ! -f "$JACOCO_CLI" ]; then
  curl -L -o "$JACOCO_CLI" "https://repo1.maven.org/maven2/org/jacoco/org.jacoco.cli/$JACOCO_VERSION/org.jacoco.cli-$JACOCO_VERSION-nodeps.jar"
fi

CLASSPATH="$LIB_DIR/*"

# Compile application sources
"$JAVAC" -d "$TARGET_DIR/classes" -cp "$CLASSPATH" "$SRC_DIR"/com/example/*.java

# Compile test sources
"$JAVAC" -d "$TARGET_DIR/test-classes" -cp "$TARGET_DIR/classes:$CLASSPATH" "$TEST_SRC_DIR"/com/example/*.java

REPORT_FILE="$REPORT_DIR/test-report.txt"
TEST_CLASSES=(
  com.example.UserTest
  com.example.UserRepositoryTest
  com.example.GreetingServiceTest
  com.example.AppConfigTest
  com.example.ApplicationTest
)

TEST_CP="$TARGET_DIR/test-classes:$TARGET_DIR/classes:$CLASSPATH"
JACOCO_EXEC="$TARGET_DIR/jacoco.exec"
HTML_REPORT_DIR="$TARGET_DIR/site/jacoco"
mkdir -p "$HTML_REPORT_DIR"

echo "Running tests and generating report at $REPORT_FILE"
{
  echo "Test report generated by build.sh"
  echo "Project: spring4-basic"
  echo "Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")"
  echo
  "$JAVA" -javaagent:"$JACOCO_AGENT"=destfile="$JACOCO_EXEC",append=false -cp "$TEST_CP" org.junit.runner.JUnitCore "${TEST_CLASSES[@]}"
} | tee "$REPORT_FILE"

if ! grep -q '^OK (' "$REPORT_FILE"; then
  echo "ERROR: some tests failed. See $REPORT_FILE"
  exit 1
fi

echo "Generating HTML coverage report at $HTML_REPORT_DIR"
"$JAVA" -jar "$JACOCO_CLI" report "$JACOCO_EXEC" \
  --classfiles "$TARGET_DIR/classes" \
  --sourcefiles "$SRC_DIR" \
  --html "$HTML_REPORT_DIR"

echo "Build complete. Test report available at $REPORT_FILE"
echo "HTML coverage report available at $HTML_REPORT_DIR/index.html"
